# coding: utf-8

# flake8: noqa
"""
    Connect API

    Welcome to the Crystal Water Monitor Connect API. This API is available to customers with an active Crystal subscription and allows you to access your pool or hot tub data programmatically.  ## Requesting an API Key  To get started, you'll need to [request an API key](https://crystalwatermonitor.com/pages/crystal-connect-api).  ## Authentication  Include your API key in every request using the `x-api-key` header:  ``` x-api-key: your-api-key-here ```  ## Rate Limiting  - **Request Speed** - Up to 10 requests per second (e.g. listing vessels then fetching details). If you send too many requests too fast you will be temporarily blocked. - **Daily Quota** - 200 requests per day, resetting every 24 hours.  **What does this mean in practice?**  Polling once every 15 minutes is recommended. Polling more aggressively will exhaust your daily quota. Also note that the Crystal Water Monitor uploads new water data at most every 20 minutes. So polling faster than every 15 minutes provides no benefit.  If you receive an HTTP 429 response, wait at least 30 seconds before retrying.  ## Maintenance Mode  The Connect API will return an HTTP 503 when it's down for maintenance. Your app should back off when this occurs. 

    The version of the OpenAPI document: 2026-06-04T21:49:37Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from ..models.connect_api_action_v1 import ConnectAPIActionV1
from ..models.connect_api_reading_types_v1 import ConnectAPIReadingTypesV1
from ..models.connect_api_reading_v1 import ConnectAPIReadingV1
from ..models.connect_api_readings_v1 import ConnectAPIReadingsV1
from ..models.connect_api_account_vessel_disc_v1 import ConnectApiAccountVesselDiscV1
from ..models.connect_api_account_vessel_summary_v1 import ConnectApiAccountVesselSummaryV1
from ..models.connect_api_account_vessel_v1 import ConnectApiAccountVesselV1
from ..models.connect_api_get_account_vessels_v1 import ConnectApiGetAccountVesselsV1
from ..models.connect_v1_vessels_vessel_id_get400_response import ConnectV1VesselsVesselIdGet400Response
from ..models.reading_range_v1 import ReadingRangeV1
from ..models.reading_sources_v1 import ReadingSourcesV1
from ..models.reading_statuses import ReadingStatuses
from ..models.reading_units import ReadingUnits
from ..models.water_status_color import WaterStatusColor

