# coding: utf-8

"""
    Connect API

    Welcome to the Crystal Water Monitor Connect API. This API is available to customers with an active Crystal subscription and allows you to access your pool or hot tub data programmatically.  ## Requesting an API Key  To get started, you'll need to [request an API key](https://crystalwatermonitor.com/pages/crystal-connect-api).  ## Authentication  Include your API key in every request using the `x-api-key` header:  ``` x-api-key: your-api-key-here ```  ## Rate Limiting  - **Request Speed** - Up to 10 requests per second (e.g. listing vessels then fetching details). If you send too many requests too fast you will be temporarily blocked. - **Daily Quota** - 200 requests per day, resetting every 24 hours.  **What does this mean in practice?**  Polling once every 15 minutes is recommended. Polling more aggressively will exhaust your daily quota. Also note that the Crystal Water Monitor uploads new water data at most every 20 minutes. So polling faster than every 15 minutes provides no benefit.  If you receive an HTTP 429 response, wait at least 30 seconds before retrying.  ## Maintenance Mode  The Connect API will return an HTTP 503 when it's down for maintenance. Your app should back off when this occurs. 

    The version of the OpenAPI document: 2026-06-04T21:49:37Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ConnectAPIReadingTypesV1(str, Enum):
    """
    ConnectAPIReadingTypesV1
    """

    """
    allowed enum values
    """
    PH = 'ph'
    ORP = 'orp'
    WATERTEMP = 'waterTemp'
    TOTALALKALINITY = 'totalAlkalinity'
    TOTALHARDNESS = 'totalHardness'
    CYANURICACID = 'cyanuricAcid'
    FREECHLORINE = 'freeChlorine'
    TOTALCHLORINE = 'totalChlorine'
    BROMINE = 'bromine'
    TOTALDISSOLVEDSOLIDS = 'totalDissolvedSolids'
    SALT = 'salt'
    PHOSPHATES = 'phosphates'
    BATTERY = 'battery'
    WIFIRSSI = 'wifiRssi'
    SMARTCHLOR = 'smartChlor'
    LSI = 'lsi'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ConnectAPIReadingTypesV1 from a JSON string"""
        return cls(json.loads(json_str))


