# coding: utf-8

"""
    Connect API

    Welcome to the Crystal Water Monitor Connect API. This API is available to customers with an active Crystal subscription and allows you to access your pool or hot tub data programmatically.  ## Requesting an API Key  To get started, you'll need to [request an API key](https://crystalwatermonitor.com/pages/crystal-connect-api).  ## Authentication  Include your API key in every request using the `x-api-key` header:  ``` x-api-key: your-api-key-here ```  ## Rate Limiting  - **Request Speed** - Up to 10 requests per second (e.g. listing vessels then fetching details). If you send too many requests too fast you will be temporarily blocked. - **Daily Quota** - 200 requests per day, resetting every 24 hours.  **What does this mean in practice?**  Polling once every 15 minutes is recommended. Polling more aggressively will exhaust your daily quota. Also note that the Crystal Water Monitor uploads new water data at most every 20 minutes. So polling faster than every 15 minutes provides no benefit.  If you receive an HTTP 429 response, wait at least 30 seconds before retrying.  ## Maintenance Mode  The Connect API will return an HTTP 503 when it's down for maintenance. Your app should back off when this occurs. 

    The version of the OpenAPI document: 2026-06-04T21:49:37Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConnectV1VesselsVesselIdGet400Response(BaseModel):
    """
    ConnectV1VesselsVesselIdGet400Response
    """ # noqa: E501
    message: StrictStr
    __properties: ClassVar[List[str]] = ["message"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConnectV1VesselsVesselIdGet400Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConnectV1VesselsVesselIdGet400Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "message": obj.get("message")
        })
        return _obj


