# coding: utf-8

# flake8: noqa
"""
    Connect API

    Welcome to the Crystal Water Monitor Connect API. This API is available to customers with an active Crystal subscription and allows you to access your vessel and water quality data programmatically.  ## Getting an API Key  To get started, you'll need an API key. Please open a support ticket in the Crystal app and our customer care team will get you set up.  ## Authentication  Include your API key in every request using the `x-api-key` header:  ``` x-api-key: your-api-key-here ```

    The version of the OpenAPI document: 2026-06-04T15:55:27Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from connect_api.models.connect_api_action_v1 import ConnectAPIActionV1
from connect_api.models.connect_api_reading_types_v1 import ConnectAPIReadingTypesV1
from connect_api.models.connect_api_reading_v1 import ConnectAPIReadingV1
from connect_api.models.connect_api_readings_v1 import ConnectAPIReadingsV1
from connect_api.models.connect_api_account_vessel_disc_v1 import ConnectApiAccountVesselDiscV1
from connect_api.models.connect_api_account_vessel_summary_v1 import ConnectApiAccountVesselSummaryV1
from connect_api.models.connect_api_account_vessel_v1 import ConnectApiAccountVesselV1
from connect_api.models.connect_api_get_account_vessels_v1 import ConnectApiGetAccountVesselsV1
from connect_api.models.connect_v1_vessels_vessel_id_get400_response import ConnectV1VesselsVesselIdGet400Response
from connect_api.models.reading_range_v1 import ReadingRangeV1
from connect_api.models.reading_sources_v1 import ReadingSourcesV1
from connect_api.models.reading_statuses import ReadingStatuses
from connect_api.models.reading_units import ReadingUnits
from connect_api.models.water_status_color import WaterStatusColor

