# coding: utf-8

"""
    Connect API

    Welcome to the Crystal Water Monitor Connect API. This API is available to customers with an active Crystal subscription and allows you to access your vessel and water quality data programmatically.  ## Getting an API Key  To get started, you'll need an API key. Please open a support ticket in the Crystal app and our customer care team will get you set up.  ## Authentication  Include your API key in every request using the `x-api-key` header:  ``` x-api-key: your-api-key-here ```

    The version of the OpenAPI document: 2026-06-04T15:55:27Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from connect_api.models.connect_api_reading_v1 import ConnectAPIReadingV1
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConnectAPIReadingsV1(BaseModel):
    """
    ConnectAPIReadingsV1
    """ # noqa: E501
    ph: Optional[ConnectAPIReadingV1] = None
    orp: Optional[ConnectAPIReadingV1] = None
    water_temp: Optional[ConnectAPIReadingV1] = Field(default=None, alias="waterTemp")
    total_alkalinity: Optional[ConnectAPIReadingV1] = Field(default=None, alias="totalAlkalinity")
    total_hardness: Optional[ConnectAPIReadingV1] = Field(default=None, alias="totalHardness")
    cyanuric_acid: Optional[ConnectAPIReadingV1] = Field(default=None, alias="cyanuricAcid")
    free_chlorine: Optional[ConnectAPIReadingV1] = Field(default=None, alias="freeChlorine")
    total_chlorine: Optional[ConnectAPIReadingV1] = Field(default=None, alias="totalChlorine")
    bromine: Optional[ConnectAPIReadingV1] = None
    total_dissolved_solids: Optional[ConnectAPIReadingV1] = Field(default=None, alias="totalDissolvedSolids")
    salt: Optional[ConnectAPIReadingV1] = None
    phosphates: Optional[ConnectAPIReadingV1] = None
    wifi_rssi: Optional[ConnectAPIReadingV1] = Field(default=None, alias="wifiRssi")
    battery: Optional[ConnectAPIReadingV1] = None
    smart_chlor: Optional[ConnectAPIReadingV1] = Field(default=None, alias="smartChlor")
    lsi: Optional[ConnectAPIReadingV1] = None
    __properties: ClassVar[List[str]] = ["ph", "orp", "waterTemp", "totalAlkalinity", "totalHardness", "cyanuricAcid", "freeChlorine", "totalChlorine", "bromine", "totalDissolvedSolids", "salt", "phosphates", "wifiRssi", "battery", "smartChlor", "lsi"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConnectAPIReadingsV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ph
        if self.ph:
            _dict['ph'] = self.ph.to_dict()
        # override the default output from pydantic by calling `to_dict()` of orp
        if self.orp:
            _dict['orp'] = self.orp.to_dict()
        # override the default output from pydantic by calling `to_dict()` of water_temp
        if self.water_temp:
            _dict['waterTemp'] = self.water_temp.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_alkalinity
        if self.total_alkalinity:
            _dict['totalAlkalinity'] = self.total_alkalinity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_hardness
        if self.total_hardness:
            _dict['totalHardness'] = self.total_hardness.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cyanuric_acid
        if self.cyanuric_acid:
            _dict['cyanuricAcid'] = self.cyanuric_acid.to_dict()
        # override the default output from pydantic by calling `to_dict()` of free_chlorine
        if self.free_chlorine:
            _dict['freeChlorine'] = self.free_chlorine.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_chlorine
        if self.total_chlorine:
            _dict['totalChlorine'] = self.total_chlorine.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bromine
        if self.bromine:
            _dict['bromine'] = self.bromine.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_dissolved_solids
        if self.total_dissolved_solids:
            _dict['totalDissolvedSolids'] = self.total_dissolved_solids.to_dict()
        # override the default output from pydantic by calling `to_dict()` of salt
        if self.salt:
            _dict['salt'] = self.salt.to_dict()
        # override the default output from pydantic by calling `to_dict()` of phosphates
        if self.phosphates:
            _dict['phosphates'] = self.phosphates.to_dict()
        # override the default output from pydantic by calling `to_dict()` of wifi_rssi
        if self.wifi_rssi:
            _dict['wifiRssi'] = self.wifi_rssi.to_dict()
        # override the default output from pydantic by calling `to_dict()` of battery
        if self.battery:
            _dict['battery'] = self.battery.to_dict()
        # override the default output from pydantic by calling `to_dict()` of smart_chlor
        if self.smart_chlor:
            _dict['smartChlor'] = self.smart_chlor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of lsi
        if self.lsi:
            _dict['lsi'] = self.lsi.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConnectAPIReadingsV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ph": ConnectAPIReadingV1.from_dict(obj["ph"]) if obj.get("ph") is not None else None,
            "orp": ConnectAPIReadingV1.from_dict(obj["orp"]) if obj.get("orp") is not None else None,
            "waterTemp": ConnectAPIReadingV1.from_dict(obj["waterTemp"]) if obj.get("waterTemp") is not None else None,
            "totalAlkalinity": ConnectAPIReadingV1.from_dict(obj["totalAlkalinity"]) if obj.get("totalAlkalinity") is not None else None,
            "totalHardness": ConnectAPIReadingV1.from_dict(obj["totalHardness"]) if obj.get("totalHardness") is not None else None,
            "cyanuricAcid": ConnectAPIReadingV1.from_dict(obj["cyanuricAcid"]) if obj.get("cyanuricAcid") is not None else None,
            "freeChlorine": ConnectAPIReadingV1.from_dict(obj["freeChlorine"]) if obj.get("freeChlorine") is not None else None,
            "totalChlorine": ConnectAPIReadingV1.from_dict(obj["totalChlorine"]) if obj.get("totalChlorine") is not None else None,
            "bromine": ConnectAPIReadingV1.from_dict(obj["bromine"]) if obj.get("bromine") is not None else None,
            "totalDissolvedSolids": ConnectAPIReadingV1.from_dict(obj["totalDissolvedSolids"]) if obj.get("totalDissolvedSolids") is not None else None,
            "salt": ConnectAPIReadingV1.from_dict(obj["salt"]) if obj.get("salt") is not None else None,
            "phosphates": ConnectAPIReadingV1.from_dict(obj["phosphates"]) if obj.get("phosphates") is not None else None,
            "wifiRssi": ConnectAPIReadingV1.from_dict(obj["wifiRssi"]) if obj.get("wifiRssi") is not None else None,
            "battery": ConnectAPIReadingV1.from_dict(obj["battery"]) if obj.get("battery") is not None else None,
            "smartChlor": ConnectAPIReadingV1.from_dict(obj["smartChlor"]) if obj.get("smartChlor") is not None else None,
            "lsi": ConnectAPIReadingV1.from_dict(obj["lsi"]) if obj.get("lsi") is not None else None
        })
        return _obj


