# coding: utf-8

"""
    Connect API

    Welcome to the Crystal Water Monitor Connect API. This API is available to customers with an active Crystal subscription and allows you to access your vessel and water quality data programmatically.  ## Getting an API Key  To get started, you'll need an API key. Please open a support ticket in the Crystal app and our customer care team will get you set up.  ## Authentication  Include your API key in every request using the `x-api-key` header:  ``` x-api-key: your-api-key-here ```

    The version of the OpenAPI document: 2026-06-04T15:55:27Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from connect_api.models.connect_api_account_vessel_summary_v1 import ConnectApiAccountVesselSummaryV1
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConnectApiGetAccountVesselsV1(BaseModel):
    """
    ConnectApiGetAccountVesselsV1
    """ # noqa: E501
    vessels: List[ConnectApiAccountVesselSummaryV1]
    __properties: ClassVar[List[str]] = ["vessels"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConnectApiGetAccountVesselsV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in vessels (list)
        _items = []
        if self.vessels:
            for _item_vessels in self.vessels:
                if _item_vessels:
                    _items.append(_item_vessels.to_dict())
            _dict['vessels'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConnectApiGetAccountVesselsV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "vessels": [ConnectApiAccountVesselSummaryV1.from_dict(_item) for _item in obj["vessels"]] if obj.get("vessels") is not None else None
        })
        return _obj


