# coding: utf-8

"""
    Connect API

    Welcome to the Crystal Water Monitor Connect API. This API is available to customers with an active Crystal subscription and allows you to access your vessel and water quality data programmatically.  ## Getting an API Key  To get started, you'll need an API key. Please open a support ticket in the Crystal app and our customer care team will get you set up.  ## Authentication  Include your API key in every request using the `x-api-key` header:  ``` x-api-key: your-api-key-here ```

    The version of the OpenAPI document: 2026-06-04T15:55:27Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from connect_api.models.reading_range_v1 import ReadingRangeV1
from connect_api.models.reading_sources_v1 import ReadingSourcesV1
from connect_api.models.reading_statuses import ReadingStatuses
from connect_api.models.reading_types_v1 import ReadingTypesV1
from connect_api.models.reading_units import ReadingUnits
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConnectAPIReadingV1(BaseModel):
    """
    ConnectAPIReadingV1
    """ # noqa: E501
    reading_type: ReadingTypesV1 = Field(alias="readingType")
    value: Optional[Union[StrictFloat, StrictInt]] = None
    range: Optional[ReadingRangeV1] = None
    unit: ReadingUnits
    unit_title: Optional[StrictStr] = Field(default=None, alias="unitTitle")
    var_date: datetime = Field(alias="date")
    source: Optional[ReadingSourcesV1] = None
    status: ReadingStatuses
    status_since_date: Optional[datetime] = Field(default=None, alias="statusSinceDate")
    abbreviation: StrictStr
    title: StrictStr
    __properties: ClassVar[List[str]] = ["readingType", "value", "range", "unit", "unitTitle", "date", "source", "status", "statusSinceDate", "abbreviation", "title"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConnectAPIReadingV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of range
        if self.range:
            _dict['range'] = self.range.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConnectAPIReadingV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "readingType": obj.get("readingType"),
            "value": obj.get("value"),
            "range": ReadingRangeV1.from_dict(obj["range"]) if obj.get("range") is not None else None,
            "unit": obj.get("unit"),
            "unitTitle": obj.get("unitTitle"),
            "date": obj.get("date"),
            "source": obj.get("source"),
            "status": obj.get("status"),
            "statusSinceDate": obj.get("statusSinceDate"),
            "abbreviation": obj.get("abbreviation"),
            "title": obj.get("title")
        })
        return _obj


