# coding: utf-8

"""
    Connect API

    Welcome to the Crystal Water Monitor Connect API. This API is available to customers with an active Crystal subscription and allows you to access your vessel and water quality data programmatically.  ## Getting an API Key  To get started, you'll need an API key. Please open a support ticket in the Crystal app and our customer care team will get you set up.  ## Authentication  Include your API key in every request using the `x-api-key` header:  ``` x-api-key: your-api-key-here ```

    The version of the OpenAPI document: 2026-06-04T15:55:27Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from connect_api.models.connect_api_account_vessel_disc_v1 import ConnectApiAccountVesselDiscV1
from connect_api.models.connect_api_action_v1 import ConnectAPIActionV1
from connect_api.models.connect_api_readings_v1 import ConnectAPIReadingsV1
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConnectApiAccountVesselV1(BaseModel):
    """
    ConnectApiAccountVesselV1
    """ # noqa: E501
    vessel_id: StrictInt = Field(alias="vesselId")
    type: StrictStr
    volume_gallons: Union[StrictFloat, StrictInt] = Field(alias="volumeGallons")
    disc: ConnectApiAccountVesselDiscV1
    readings: ConnectAPIReadingsV1
    actions: List[ConnectAPIActionV1]
    __properties: ClassVar[List[str]] = ["vesselId", "type", "volumeGallons", "disc", "readings", "actions"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConnectApiAccountVesselV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of disc
        if self.disc:
            _dict['disc'] = self.disc.to_dict()
        # override the default output from pydantic by calling `to_dict()` of readings
        if self.readings:
            _dict['readings'] = self.readings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in actions (list)
        _items = []
        if self.actions:
            for _item_actions in self.actions:
                if _item_actions:
                    _items.append(_item_actions.to_dict())
            _dict['actions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConnectApiAccountVesselV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "vesselId": obj.get("vesselId"),
            "type": obj.get("type"),
            "volumeGallons": obj.get("volumeGallons"),
            "disc": ConnectApiAccountVesselDiscV1.from_dict(obj["disc"]) if obj.get("disc") is not None else None,
            "readings": ConnectAPIReadingsV1.from_dict(obj["readings"]) if obj.get("readings") is not None else None,
            "actions": [ConnectAPIActionV1.from_dict(_item) for _item in obj["actions"]] if obj.get("actions") is not None else None
        })
        return _obj


