# coding: utf-8

"""
    Connect API

    Welcome to the Crystal Water Monitor Connect API. This API is available to customers with an active Crystal subscription and allows you to access your vessel and water quality data programmatically.  ## Getting an API Key  To get started, you'll need an API key. Please open a support ticket in the Crystal app and our customer care team will get you set up.  ## Authentication  Include your API key in every request using the `x-api-key` header:  ``` x-api-key: your-api-key-here ```

    The version of the OpenAPI document: 2026-06-04T15:55:27Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ReadingUnits(str, Enum):
    """
    ReadingUnits
    """

    """
    allowed enum values
    """
    PH = 'ph'
    MV = 'mV'
    C = 'C'
    F = 'F'
    PPM = 'ppm'
    PPB = 'ppb'
    DB = 'db'
    PERCENT = '%'
    LSI = 'lsi'
    MS = 'ms'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ReadingUnits from a JSON string"""
        return cls(json.loads(json_str))


