# coding: utf-8

# flake8: noqa

"""
    Connect API

    Welcome to the Crystal Water Monitor Connect API. This API is available to customers with an active Crystal subscription and allows you to access your vessel and water quality data programmatically.  ## Getting an API Key  To get started, you'll need an API key. Please open a support ticket in the Crystal app and our customer care team will get you set up.  ## Authentication  Include your API key in every request using the `x-api-key` header:  ``` x-api-key: your-api-key-here ```

    The version of the OpenAPI document: 2026-06-04T15:55:27Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ConnectAPIActionV1",
    "ConnectAPIReadingV1",
    "ConnectAPIReadingsV1",
    "ConnectApiAccountVesselDiscV1",
    "ConnectApiAccountVesselSummaryV1",
    "ConnectApiAccountVesselV1",
    "ConnectApiGetAccountVesselsV1",
    "ConnectV1VesselsVesselIdGet400Response",
    "ReadingRangeV1",
    "ReadingSourcesV1",
    "ReadingStatuses",
    "ReadingTypesV1",
    "ReadingUnits",
]

# import apis into sdk package
from connect_api.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from connect_api.api_response import ApiResponse as ApiResponse
from connect_api.api_client import ApiClient as ApiClient
from connect_api.configuration import Configuration as Configuration
from connect_api.exceptions import OpenApiException as OpenApiException
from connect_api.exceptions import ApiTypeError as ApiTypeError
from connect_api.exceptions import ApiValueError as ApiValueError
from connect_api.exceptions import ApiKeyError as ApiKeyError
from connect_api.exceptions import ApiAttributeError as ApiAttributeError
from connect_api.exceptions import ApiException as ApiException

# import models into sdk package
from connect_api.models.connect_api_action_v1 import ConnectAPIActionV1 as ConnectAPIActionV1
from connect_api.models.connect_api_reading_v1 import ConnectAPIReadingV1 as ConnectAPIReadingV1
from connect_api.models.connect_api_readings_v1 import ConnectAPIReadingsV1 as ConnectAPIReadingsV1
from connect_api.models.connect_api_account_vessel_disc_v1 import ConnectApiAccountVesselDiscV1 as ConnectApiAccountVesselDiscV1
from connect_api.models.connect_api_account_vessel_summary_v1 import ConnectApiAccountVesselSummaryV1 as ConnectApiAccountVesselSummaryV1
from connect_api.models.connect_api_account_vessel_v1 import ConnectApiAccountVesselV1 as ConnectApiAccountVesselV1
from connect_api.models.connect_api_get_account_vessels_v1 import ConnectApiGetAccountVesselsV1 as ConnectApiGetAccountVesselsV1
from connect_api.models.connect_v1_vessels_vessel_id_get400_response import ConnectV1VesselsVesselIdGet400Response as ConnectV1VesselsVesselIdGet400Response
from connect_api.models.reading_range_v1 import ReadingRangeV1 as ReadingRangeV1
from connect_api.models.reading_sources_v1 import ReadingSourcesV1 as ReadingSourcesV1
from connect_api.models.reading_statuses import ReadingStatuses as ReadingStatuses
from connect_api.models.reading_types_v1 import ReadingTypesV1 as ReadingTypesV1
from connect_api.models.reading_units import ReadingUnits as ReadingUnits

